### ISSUE TITLE
Lagre lister over alle studenter i kurs:

### ISSUE THREAD

**Issue by olehermanse** [fui/fui-kk#20]
kommandoen `lsng`kan brukes til å finne alle studentene som tar et kurs på ifi:
```
[olehelg@vetur ~]$ lsng sinf1000
bruker-drift
brukerto
brukertre
brukerfyr
```

En liten oppgave er å kjøre denne kommandoen for alle kurst i `course_list.json` (generert av `download-course-list.py`) og lagre resultatet i txt filer:
```
[olehelg@vetur ~]$ lsng sinf1000 > INF1000.txt
```

**OBS:** legg merke til at gruppene har små bokstaver, men kurskodene er med store bokstaver. I kurs hvor det er en bindestrek i kurskoden fjernes denne, så: `INF-BIO5121` blir 'sinfbio5121'

**Comment by evestera** [comment]
Hvordan er egentlig cutoff på `lsng` i forhold til hva vi ideellt ønsker? Med `lsng` får man jo med folk som har droppet faget (i alle fall ser det slik ut), men samtidig får man heller ikke med alle som *var* oppmeldt.

**Comment by olehermanse** [comment]
lsng er ikke optimalt, men det er det eneste alternativet vi har AFAIK. Heldigvis filtrerer nettskjema ut noen brukernavn i invitasjonsprosessen, *-drift brukernavn f.eks.
