### ISSUE TITLE
Endre mappestruktur i data

### ISSUE THREAD

**Issue by olehermanse** [fui/fui-kk#31]
Jeg synes hver semestermappe burde være delt opp i inputs og outputs:

Hvor outputs er trygt å slette.
`data/V2016/inputs`: `md`(fra kk),`json`(fra download), `html`(fra download), `tsv`(fra download)

`data/V2016/outputs`: `json`(genererte), `tex`,`report`

**Comment by evestera** [comment]
Fixed in #33
