### ISSUE TITLE
Semester.py breaks due to spelling correction in questions.

### ISSUE THREAD

**Issue by Berstad** [fui/fui-kk#59]
Someone corrected the spelling in the V2017 forms to say:

> Hva er ditt generelle inntrykk av kurset 

instead of 

> Hva er det generelle intrykk av kurset.

This is great, but as semester.py explicitly declares the latter as the general question, it breaks for V2017 forms. If you change semester.py to the corrected spelling, it no longer works for previous semesters forms. This is a problem if you are working on several semesters of forms simultaneously. 

The specific error is:
> python3 src/semester.py
> Traceback (most recent call last):
>   File "src/semester.py", line 50, in <module>
>     main("./data/"+sem)
>   File "src/semester.py", line 41, in main
>     semester_data[course_name] = get_course_data(semester_dir+"/outputs/stats/"+f)
>   File "src/semester.py", line 29, in get_course_data
>     course[general_question] = course["questions"][general_question]
> KeyError: 'Hva er ditt generelle intrykk av kurset?'
> Makefile:35: recipe for target 'json' failed
> make: *** [json] Error 1

**Comment by evestera** [comment]
En rask fiks kan være så enkel som å erstatte [dagens linje 29](https://github.com/fui/fui-kk/blob/6f6516706f9f70026ab9063350ba27ff8e2f9039/src/semester.py#L29) med følgende:

```py
try:
    course[general_question] = course["questions"][general_question]
except KeyError, e:
    general_question = "sett inn alternativ skrivemåte her"
    course[general_question] = course["questions"][general_question]
```

På sikt burde man jo helst finne en litt mer vedlikeholdbar måte å gjøre det på.

**Comment by olehermanse** [comment]
For å være litt pedantisk så er egentlig en endring i spørsmålsteksten et nytt spørsmål, og kan påvirke svarene. Jeg vet at jeg har skrevet en del kode for å kunne enkelt legge til spørsmål og svaralternativer, men jeg skal se mer på det til helgen, med de nye resultatene.

Ville ikke kalt dette en bug, det er en utfordring jeg/vi har vært klar over, men implementasjonen er ikke der helt enda. Systemet er ikke ferdig utviklet for å håndtere nye / endrede skjemaer.

**Comment by Berstad** [comment]
Ok, det virker heller ikke som om genereringen av .json filer i outputs/stats for de kursene med skjema på engelsk (ie. masterkurs) fungerer heller. Resultatet blir:

>"language": null,
> "questions": {}

Da feiler også semester.py av åpenbare grunner. Det haster litt at dette funker for de nye skjemaene siden rådataen skal publiseres.
