### ISSUE TITLE
download fungerer ikkje

### ISSUE THREAD

**Issue by martava** [fui/fui-kk#62]
eg prøver å køyre make download, får denne feilen:
python3 src/sort_downloads.py --delete -i downloads -o data -e "(INF9)|(testskjema)|(\*\*\*)|(XXX)"
Skipped - No semester: downloads/formdata.dat
"Warning: Please delete the downloads folder once per semester"
"         after closing the forms, to ensure that up to date"
"         reports are downloaded. (The download script will not"
"         redownload forms with ID in downloaded.txt)"

**Comment by olehermanse** [comment]
I make filen ser man at make download kjører 2 scripts, først `download_reports` og så `sort_downloads`. Nedlastingen logger inn på https://nettskjema.uio.no og laster ned rapporter der fra, til downloads mappa, hvis du sjekker den mappa er den nesten tom, så ingenting ble lastet ned. Prøv å logge inn på nettskjema for å sjekke at passord er riktig osv. 

Problemet var i dette tilfellet at nettskjema hadde nye vilkår man må godkjenne. Jeg logget inn med fui brukeren på nettskjema, godtok, og nå fungerer det.
