### ISSUE TITLE
Feil på "Hva er ditt generelle inntrykk av kurset" 

### ISSUE THREAD

**Issue by martava** [fui/fui-kk#63]
Køyrer make all, får denne feilen: 
(Har kommentert ut rename-linja i makefila, og oppdatert til V2017)
```
python3 src/plot_courses.py V2017
Traceback (most recent call last):
  File "src/plot_courses.py", line 116, in <module>
    plot_courses(sys.argv[1])
  File "src/plot_courses.py", line 113, in plot_courses
    generate_plots(courses, scales, semester)
  File "src/plot_courses.py", line 107, in generate_plots
    plot_course(c, courses, outdir, scales, semester_name)
  File "src/plot_courses.py", line 74, in plot_course
    scores.append(course[semester][semester_question]["average"])
KeyError: 'Hva er ditt generelle intrykk av kurset?'
make: *** [plots] Error 1
```

**Comment by olehermanse** [comment]
Feilen kommer av at den prøver å lage et gjennomsnittsplott over tid, for spørsmålet "Hva er ditt generelle intrykk av kurset?", men det siste semesteret ble en skrivefeil rettet: "Hva er ditt generelle inntrykk av kurset?".

Ser på en løsning nå, hvis ikke jeg finner på noe relativt kjapt må jeg se nærmere på det til helgen.
