### ISSUE TITLE
corses.json does not exist

### ISSUE THREAD

**Issue by martava** [fui/fui-kk#65]
Make json gir ingen error, men får masse warnings om "could not find name for course ****"

Prøver å fordele emna, får denne feilen: 
```
PS C:\Users\valen\Documents\fui-kk\src> python3 course_divide.py 8 V2017
ERROR: Could not open './data/V2017/outputs/courses.json' for read, file doesn't exist.
```

**Comment by olehermanse** [comment]
Kursene du får advarsel om er gamle nedlagte kurs, så det er ikke noe problem.

**Comment by olehermanse** [comment]
Fikser denne i løpet av helgen.

**Comment by olehermanse** [comment]
@martava Jeg så ikke nøye nok på feilmeldingen. Problemet er at du kjører python skriptet inni `src` mappen. Der er det ikke noen `./data` mappe. Dette fungerer:

```
python3 src/course_divide.py 8 V2017
```

I #66 la jeg til denne:
```
make assign-courses
```

Som burde være enklere å bruke.
