### ISSUE TITLE
Feil i make web

### ISSUE THREAD

**Issue by martava** [fui/fui-kk#71]
Får denne feilmeldinga når eg køyrer make web på linux-maskin:

bash ./src/web.sh V2017
cp: cannot stat ‘./resources/d3-charts/dist/’: No such file or directory
rename: invalid option -- 'f'

**Comment by olehermanse** [comment]
For å fikse den første feilmeldingen, kjør:
```
git submodule update --init --recursive
```

For å fikse den andre feilmeldingen, kommenter ut som dette i Makefile:
```
tex:
	# rename -v -f -S inf INF ./data/*/inputs/md/* # Only on mac
	perl -i.bak -pe 's/\x61\xCC\x8A/\xC3\xA5/g' ./data/*/inputs/md/*.md
```

Lagt til begge i #72
