### ISSUE TITLE
"Gjennomsnitt på Ifi" is missing @ spring 2017

### ISSUE THREAD

**Issue by PrebenAas** [fui/fui-kk#79]
"Gjennomsnitt på Ifi" is missing @ spring 2017 within the courses, as well as the upper page.

**Comment by olehermanse** [comment]
Where is this? Steps to reproduce? Did you upload or are you seeing this locally?

**Comment by PrebenAas** [comment]
I am referring to the dotted line, e.g. within a course: https://www.mn.uio.no/ifi/livet-rundt-studiene/organisasjoner/fui/kursevaluering/V2017/INF1010.html

The main/"upper" page: https://www.mn.uio.no/ifi/livet-rundt-studiene/organisasjoner/fui/kursevaluering/

It seems they have not been implemented or the script failed at some level when uploading this data. I did not upload, nor is this locally.

**Comment by Berstad** [comment]
This is also true for the Fall 2016 courses. eg. https://www.mn.uio.no/ifi/livet-rundt-studiene/organisasjoner/fui/kursevaluering/H2016/INF1000.html

**Comment by olehermanse** [comment]
Mostly fixed in #82 . Will create a new more relevant issue.
