### ISSUE TITLE
Graf for masterfag på engelsk

### ISSUE THREAD

**Issue by martava** [fui/fui-kk#89]
I grafene generert til rapporten så står namnet på grafen i masterfaga ("Generell vurdering fra XXXX") på norsk, medan resten er på engelsk. Fint om den kan bli på engelsk også.

**Comment by olehermanse** [comment]
Takk, skal se på denne i løpet av påsken!

**Comment by olehermanse** [comment]
https://github.com/fui/fui-kk/pull/90
